command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: DATABRICKS_HOST
    value: https://fevm-cmegdemos.cloud.databricks.com
  - name: LAKEBASE_INSTANCE_NAME
    value: telco-call-center
  - name: LAKEBASE_DB_NAME
    value: public
  - name: DATABRICKS_AGENT_ENDPOINT
    value: https://fevm-cmegdemos.cloud.databricks.com/serving-endpoints/agents_cmegdemos_catalog-telco_call_center_analytics-analytics/invocations